### ISSUE TITLE
User got 'Credential Failed' error while trying to make a machine 'Always On'

### ISSUE THREAD

**Issue by diclee** [koding/koding#9076] opened 2016-09-20 23:26 UTC
## Current Behavior

It's happening only on a specific account and a machine.
http://recordit.co/hAJ14N5hrf
##

**Comment by gokmen** [comment] 2017-02-01 21:55
couldn't reproduce, it must be fixed with https://github.com/koding/koding/pull/9319 please do not hesitate to re-open it again if it's reproducible.

**Closed by gokmen** 2017-02-01 21:55 UTC
Labels: A-Bug, Component-Stacks
