### ISSUE TITLE
Old sessions are not listed in 'Sessions' list.

### ISSUE THREAD

**Issue by diclee** [koding/koding#9580] opened 2016-11-15 17:07 UTC
## Current Behavior
![image](https://cloud.githubusercontent.com/assets/8261892/20315467/a14d3370-ab66-11e6-9eb2-c5e80bed6cd8.png)

**Comment by hakankaradis** [comment] 2016-11-15 19:52
@diclee Couldn't reproduce.
Active tag style fixed.
![](https://monosnap.com/file/KFIhOtt8c5mi2ZuNzeyMORHwMyJ3Ce.png)

**Comment by hakankaradis** [comment] 2016-11-18 19:11
I have tested on production and sandbox, It looks ok.
Closing this issue for now, please reopen If you can produce again. /cc: @diclee

**Closed by hakankaradis** 2016-11-18 19:11 UTC
Labels: A-Bug, Component-Dashboard, Priority-Low
