### ISSUE TITLE
Docker compose now redirects to https://www.koding.com/farewell-solo

### ISSUE THREAD

**Issue by joshstrange** [koding/koding#8890] opened 2016-08-22 20:19 UTC
## Expected Behavior
After running:
    docker-compose up -d
I should be able to visit localhost:8090 and use koding 

## Current Behavior
After taking to the time to upgrade my docker and docker-compose and visited the url and was redirected to https://www.koding.com/farewell-solo has this been discontinued?

## Context
I wanted to try out Koding and it appears you no longer support the self-hosted version

## Your Environment
* Version used: latest
* Operating System and version (desktop or mobile): Ubuntu 14.04

**Comment by chandruxp** [comment] 2016-08-23 12:28
same problem here..

**Comment by szkl** [comment] 2016-08-23 16:10
This is the intended behaviour for accessing home page after solo version is discontinued. You should be able to access a team site login page via `team-name.localhost:8090`. It should let you create a team.

I will reply back with how to improve this situation later.

**Comment by adamgoose** [comment] 2016-08-23 16:11
When I set the host to `koding.domain.com`, and access it at `gitlab.koding.domain.com`, I still get redirected.

**Comment by adamgoose** [comment] 2016-08-23 16:13
Note, I'm behind a reverse HTTP proxy that does SSL termination.

**Comment by adamgoose** [comment] 2016-08-23 17:35
It appears as though the Docker container makes FAR too many assumptions regarding how the instance can be accessed. I'd like the ability to specify one ENV that declares how the instance can be reached, i.e. https://koding.domain.com

**Comment by chandruxp** [comment] 2016-08-24 00:23
Somehow http://localhost:8090/Teams worked for me..

**Comment by szkl** [comment] 2016-09-02 20:43
Redirection has been removed. Patch is landed on master. I've pushed a new koding container image for koding/docker-compose repository users. If you've cloned koding/koding repository to run docker-compose then you can just have to pull latest changes merged into master branch.

Feel free to reopen issue if you're still experiencing problems.

**Closed by szkl** 2016-09-02 20:43 UTC
Labels: A-Bug
