### ISSUE TITLE
ShadowVariables method duplicates array elements of Resource object.

### ISSUE THREAD

**Issue by ppknap** [koding/koding#9346] opened 2016-10-19 22:02 UTC
If template's Resource map contains array values like `[]map[string]interface{}`, calling ShadowVariables will add values from template's ast.ObjectList tree to that resource. It should replace them instead.

## Expected Behavior
Array elements in final Resource object are not duplicated and contain valid shadowed variables.

## Current Behavior
Array elements in final Resource object are duplicated. 

## Possible Solution
1 - Rewrite ShadowVariables function so it will not use hcl pacage - this one will need some work.
2 - Hack hcl.DecodeObject function so it will merge all array elements instead of adding them. (probably bad idea but simpler that 1)
3 - ??

## Steps to Reproduce (for bugs)
Code that demonstrates the problem: https://play.golang.org/p/wtTsxinMIP

Code that causes the problem: https://github.com/koding/koding/blob/d767072a16ee25211bb6a2d20603a46060f96fb0/go/src/koding/kites/kloud/stack/provider/template.go#L217

Exact place where array variables are duplicated:
https://github.com/hashicorp/hcl/blob/master/decoder.go#L456

## Context
All users who specify array elements in their stack will end up with duplicated values. GCP instances require `disk` field to be of array type (because user can specify more than one). Because of this bug, specified disks are duplicated.

/cc @cihangir @gokmen @rjeczalik

**Comment by gokmen** [comment] 2016-10-23 07:01
This was the most annoying part of `hcl-to-json` for me, had to write something like this https://github.com/gokmen/hcl-to-json/blob/master/src/index.coffee#L152-L163 which I'm planning to replace with something better. Following examples actually tells the issue better;

in this example `foo.bar.baz` is `object`
```hcl
foo "bar" {
    baz = {
        test = 123
    }
}
```
try: https://runkit.com/gokmen/580c5fa38469b60013af02eb

but if you define it multiple times it becomes an `array`
```hcl
foo "bar" {
    baz = {
        test = 123
    }
    baz = {
        test = 345
    }
}
```
try: https://runkit.com/gokmen/580c5cedc53c3b001452b119

**Comment by rjeczalik** [comment] 2016-10-23 09:51
Interestingly, github.com/hashicorp/hcl always encodes to a slice of objects when no schema is available (generic hcl-to-json encoding). In particular this HCL:

```hcl
resource "foo" "bar" {
	baz = {
		test = 123
	}
}
```

Encodes to JSON with [this code](https://play.golang.org/p/_oiAuPTGEN) - the result looks like:

```json
{
	"resource": [
		{
			"foo": [
				{
					"bar": [
						{
							"baz": [
								{
									"test": 123
								}
							]
						}
					]
				}
			]
		}
	]
}
```

In order to make HCL decoder use proper schema, one may need to provide it explicitly instead of generic `var v interface{}` value. Then if we use such "guided" decoding, [it produces](https://play.golang.org/p/1qOQ5J0L_X) correct JSON:

```json
{
	"resource": {
		"foo": {
			"bar": {
				"baz": [
					{
						"test": 123
					}
				]
			}
		}
	}
}

```

Here the problem is if you use the same v variable as an output one for decoding, slice elements get merged instead of replaced, as one would expect. So if you [unmarshal into v 3 times](https://play.golang.org/p/tXGBVrQzYQ), then the resulting JSON will look like:

```json
{
	"resource": {
		"foo": {
			"bar": {
				"baz": [
					{
						"test": 123
					},
					{
						"test": 123
					},
					{
						"test": 123
					}
				]
			}
		}
	}
}
```

Thus the issue, and the workaround :-)

**Closed** 2016-10-26 06:24 UTC
Labels: A-Bug
